name: auto_updater_example
description: Demonstrates how to use the auto_updater plugin.
version: 1.1.0+2
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_updater:
    path: ../
  bot_toast: ^4.1.3
  flutter:
    sdk: flutter
  preference_list: ^0.0.1
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1

flutter:
  uses-material-design: true
