name: auto_updater_example
description: Demonstrates how to use the auto_updater plugin.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_updater:
    path: ../
  bot_toast: ^4.1.3
  flutter:
    sdk: flutter
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.2

flutter:
  uses-material-design: true
